Additional extends logic
notamedia/yii2-locker pull request #5
Opened 2017-12-18 06:03 UTC by alexstepankov

2017-12-18 14:12 UTC, niksamokhvalov requested changes
Хорошая работа. Но надо поработать над документированием и постараться снизить связанность разных слоёв в коде.

2017-12-18 14:12 UTC, niksamokhvalov commented on src/LockManager.php
> +    public $lockClass = Lock::class;
Тут есть пара небольших, но как мне кажется, важных проблем:

1. В коде не проверяется, что передан объект, реализующий нужный нам интерфейс. Либо нужно при инициализации проверять соответствие ожидаемому типу, либо требовать внедрения этой модели через DI в конструкторе компонента.
1. Чтобы понять или вспомнить, на что влияет это свойство, придётся перешерстить всю документацию (и скорее всего ответ не найдётся), стоит описать прямо здесь назначение этого свойства.

2017-12-18 14:12 UTC, niksamokhvalov commented on src/LockInterface.php
> + * @property string $hash - hash
По-моему, это лишнее.

2017-12-18 14:12 UTC, niksamokhvalov commented on src/LockInterface.php
> +     * Get lock
Мне кажется, этот метод достоит более подробного описания.

2017-12-18 14:12 UTC, niksamokhvalov commented on src/LockInterface.php
> +     * Get lock time left
Непонятно, в каких попугаях возвращаются значения.

2017-12-18 14:12 UTC, niksamokhvalov commented on src/LockInterface.php
> +     * @param Expression $lockedAtExpression
Здесь и в других местах комментарии не дают пояснения относительно того, что ожидается в expression-аргументах.

2017-12-18 14:12 UTC, niksamokhvalov commented on src/LockInterface.php
> + *     public function getDiff();
Этого метода нет в интерфейсе. И если честно, не понятно, что данным кодом хотелось продемонстрировать? Тут просто идёт перечень методов интерфейса.

2017-12-18 14:12 UTC, niksamokhvalov commented on src/LockInterface.php
> +use yii\web\User;
Чтобы снизить связность, лучше организовать зависимость не от компонента, а от модели `\yii\web\IdentityInterface`. Она тоже знает идентификатор пользователя.

2017-12-18 14:12 UTC, niksamokhvalov commented on CHANGELOG.md
> +### Added
Видимо, это Changed, а не Added?

2017-12-18 14:12 UTC, niksamokhvalov commented on src/Lock.php
> +                'locked_by' => \Yii::$app->getUser()->getId()
Плохо, когда есть у модели зависимость от сервисного слоя. Постарайся избавиться от этого. В данном случае, можно требовать на вход модель `\yii\web\IdentityInterface`.

2017-12-21 09:49 UTC, alexstepankov commented
@niksamokhvalov внес правки

2017-12-21 11:52 UTC, niksamokhvalov requested changes
Дошлифовать и можно релизить.

2017-12-21 11:52 UTC, niksamokhvalov commented on src/LockInterface.php
> + *     public function activate(User $user, Expression $lockedAtExpression);
Неправильный тайптинтинг. И повторюсь: непонятно, какая польза в этом примере кода, перечисляющего список методов интерфейса? Что это даёт пользователю расширения, по сравнению с просмотром пхпдоков методов интерфейса?

2017-12-21 11:52 UTC, niksamokhvalov commented on src/LockManager.php
> +        if (!\Yii::$container->has(LockInterface::class)) {
Лёш, надо эту штуку вынести в `bootstrap.php`, вот почему: некое приложение или это же расширение может затребовать реализацию `LockInterface` раньше вызова менеджера. Всегда желательно стараться конфигурироваться не на лету, а как можно раньше, на самом старте. И в этом компоненте в конструкторе просто требуй зависимость:

```php
public function __construct(array $config = [], LockInterface $lockModel)
{
      $this->lockModel = $lockModel;
        
      parent::__construct($config);
}
```

К слову, одна из прелестей DI в том, что класс, получающий зависимость, не оперирует API фреймворка (читай — не делает вызовов `Yii::$container->get()`.

2017-12-21 12:03 UTC, niksamokhvalov commented
Кстати, кажется я починил интеграцию с Трэвисом, подмерж себе свежий мастер.

2017-12-21 14:06 UTC, alexstepankov commented on src/LockInterface.php
> + *     public function activate(User $user, Expression $lockedAtExpression);
Да, такие пустые болванки бессмыслены, в `src/LockableInterface.php` приведен пример реализации, в нем я описание оставил

2017-12-21 14:07 UTC, alexstepankov commented on src/LockManager.php
> +        if (!\Yii::$container->has(LockInterface::class)) {
Добавил в bootstrap, но в конструктор инжектить нельзя, т.к мы определяем коллбек который принимает параметры и его нужно вызывать через ->get в нужных местах

2017-12-21 14:52 UTC, niksamokhvalov commented on src/LockManager.php
> +        if (!\Yii::$container->has(LockInterface::class)) {
Надо передавать просто модель блокировок, а не конкретную запись. Поэтому я в примере выше показал создание свойства `lockModel`. У тебя есть интерфейс с методом `findOrCreate` — этого клиентскому коду достаточно. Нужно изолировать код от работы с хранилищем контейнеров, иначе это никакой не DI :)

2017-12-25 15:49 UTC, alexstepankov commented on src/LockManager.php
> +        if (!\Yii::$container->has(LockInterface::class)) {
@niksamokhvalov внес правки

2017-12-27 09:25 UTC, merged